sudo: false
language: ruby
rvm:
- 2.3.1
script:
- RAILS_ENV=test bundle exec rake db:create db:migrate
- bundle exec rspec spec
deploy:
  provider: rubygems
  api_key:
    secure: Q6b64qxy3KznA87Ctb/VRmmFvf94hoM/XmbU/ZCMf3Rpyh2E8tYWFredUjoaJYtW2UlPlEvYOpkGlNCVFxV4aCcyxhRvHYqW6q0ThhPoMRqJ6prEOiwG3f5qtmm3ugdNqieeUDDsDAVmp/8Oql4O56o0obsQHqD1zBOZw+QTrbB+C/hsQUF8PYaH+iqDhCxg6q1ukJsICIR0nO1jPjUcqPQXVjCAQAjNaQt3xbaybvB/kk89HbA1KX0HOndNQn5bE3cNVTnYoG//79VMcgxWwUqe2G9Oea8yzoiXX+qthQvSHen6e59qHWbm4jyBfSLiMrVP6y3jZKB9Iuqf+2woPkjEdkKrSqUjkhF6oR7ZmDMm2ccWy7Me0SM8zoG1vusLuNRZ5dYgBaKk6a3lQRNMnV4SegLz7NR/+LLuDuFv95PrDXYj6HPFrrnwiOWfiz5qNDh34K/AaWDjoRELv8IYGbpPeb92qjWqbHvFrjpHez7ZCrqR2C9jSQNYm5HOY/lT332KXsdZ/jius3nN9sb8jr37tSN0zJZJYUNPXTtJJqaauzDKfhs5hCcFOstpKmC4u4APfEvsB1KZnyZtJv5wNF7CQ+YxZcNZS++JUsoKJB+f698P7MuEp/yMkwyEMqKyS1BnMQDhAqaSOHXB1PciHW3+uXtEQlYTf31LckozmvY=
  gem: local_resource
  on:
    tags: true
    repo: platanus/local_resource
